# Environment file to build website on each commit
# For end-users, the gds_env (darribas.org/gds_env) is recommended
name: book
channels:
  - default
  - conda-forge
dependencies:
  - python=3.7.*
  - sphinx=3.4.2
  - pip=20.3.3
  - nbconvert=5.6.1
  - pip:
      - jupyter-book>=0.9.1,<0.11
      - pyppeteer>=0.2.2