# Environment file to build website on each commit
# For end-users, the gds_env (darribas.org/gds_env) is recommended
name: book
channels:
  - default
  - conda-forge
dependencies:
  - python=3.7.*
  - sphinx=2.4.4
  - pip=20.2.4
  - nbconvert=5.6.1
  - pip:
      - jupyter-book==0.7.3
      - pyppeteer>=0.2.2
