# Book settings
title: A course on Geographic Data Science
author: Dani Arribas-Bel
#logo: logo.jpeg

execute:
  execute_notebooks: "off"
repository:
  url: https://github.com/darribas/gds_course
launch_buttons:
  binderhub_url: https://mybinder.org
  
html:
  google_analytics_id: UA-6032674-1
  extra_footer: |
    <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">A course on Geographic Data Science</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="http://darribas.org" property="cc:attributionName" rel="cc:attributionURL">Dani Arribas-Bel</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
    
sphinx:
  config:
    html_show_copyright: false